server:
  appName: "SOME_SERVICE"
  port: "8081"
  secret: "SOME_SECRET"
  mode: "debug"

database:
  dialect: pg
  dbname: "fullstack_api"
  host: "127.0.0.1"
  port: "5432"
  username: "sc_u"
  password: "password"
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50

LogConfig:
  level: 'info'
  filename: "logs/api.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3